### ISSUE TITLE
Rework settings file

### ISSUE THREAD

**Issue by ptylczynski** [CaddoBenchmark/file-parser#20]
We should to rework settings.yaml to contain more descriptive names

## Implementation suggestion
```yaml
data:
  input:
    path: data.csv
    separator: $
  extraction:
    function:
      path: extraction_function
  output:
    file:
      name: results.csv
      separator: $
  splitting:
    folding:
      method: KFOLDS
      number: 10
      runs: 10
      seeds:
        from_list: [1,2,3,4,5, 6, 7, 8, 9, 10]
```
